name: Python Application CI/CD

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.GOOGLE_GCP_SERVER }}  >> ~/.ssh/known_hosts

      - name: SSH into gcp virtual machine
        run: ssh -i ~/.ssh/id_rsa sharmi@${{ secrets.GOOGLE_GCP_SERVER }} -tt

      - name: Checkout git repo
        uses: actions/checkout@v1

