name: Python Application CI/CD

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: SSH into gcp virtual machine
        run: ssh -i ~/.ssh/id_rsa sharmi@${{ secrets.GOOGLE_GCP_SERVER }} -tt

      - name: Checkout git repo
        uses: actions/checkout@v1

