name: Python Application CI/CD

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GOOGLE_GCP_SERVER }}
          username: sharmi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: ls
