name: Python Application CI/CD

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GOOGLE_GCP_SERVER }}
          username: sharmi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd devops_crud_app
            git pull origin main
            docker build -f docker/Dockerfile -t devops_crud_app .

